### ISSUE TITLE
Any way to get this working for the Windows Store version?

### ISSUE THREAD

**Issue by SMadani** [simonowen/dirtfix#2]
This program assumes you're using the Steam version of the game. Unfortunately the Windows Store version hides away the files into read-only directory and it's difficult to find where it's actually installed (uses MSIXVC so everything is just one file). It would be great if there was a way to fix this without depending on the game's install directory - even if for example you had to start the program and select the game's process ID.

**Comment by simonowen** [comment]
It should work, assuming the Windows Store version is just a simple wrapper around the normal game.  As you said, the location tends to be harder to find, and may change when the game is updated.

Could you try manually adding the DLL to the directory?  That should mean:
- launch DiRT Rally 2.0 from the Windows store.
- Press Ctrl-Shift-Escape to launch task manager (Alt-Tab back to Window first if necessary)
- find the game process on the Details tab, right-click and select _Open file location_.
- press Ctrl-N for a new Explorer window and navigate to C:\Program Files (x86)\DirtFix
- copy _dinput8_64.dll_ to the DR 2.0 game directory in the other window.
- rename _dinput8_64.dll_ to _dinput8.dll_
- restart the DR 2.0 and check if the stutters are gone.

The default locations are only taken from Steam at the moment, as that's the version I own.  I can probably expand it to search for the Oculus store version, and the Windows store too if your test works.  I'd need to change the file copy to prompt for elevation if needed, but that shouldn't be too difficult to add.

**Comment by fixel99** [comment]
Have tried this exactly but doesn't seem to remove stutter unfortunately :/

**Comment by simonowen** [comment]
I've just signed up for _Xbox Game Pass for PC_ so I can install the Microsoft Store version here.  I'll run some tests and see whether it can be made to work.

**Comment by SMadani** [comment]
Thanks! Unfortunately I've not been able to try this due to a recent update that has corrupted my installation.

**Comment by simonowen** [comment]
On my system the game ended up in `C:\Program Files\ModifiableWindowsApps\DiRT Rally 2.0`.  Manually copying `dinput8_64.dll` from the DirtFix installation into that directory and then renaming it to `dinput8.dll` definitely works.  If you're still seeing glitches then they must be something unrelated to input polling.

I'll update the frontend to scan the Microsoft and Oculus store locations for supported games, so they should automatically appear in the list. I'll also need to change the file copy to handle protected locations (such as _Program Files_), which will prompt for elevation if needed. I hope to have an updated version in the next day or so.

**Comment by simonowen** [comment]
I've just release [v1.4](https://github.com/simonowen/dirtfix/releases/tag/v1.4), which should resolve this.

As mentioned above, I've confirmed this does apply the fix to my Microsoft Store copy of DR 2.0. If you're still experiencing stutter after activating it you may have a different issue.
