### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by JonnyThree** [simonowen/dirtfix#3]
Hello i use x360ce (XBox controller emulator) with dirt rally 2.0, that works with his custom xinput9_1_0.dll library. Do you know if this mod is compatible with that controller emulator?

**Comment by simonowen** [comment]
DirtFix uses a custom dinput8.dll to stop DirectInput polling.  That shouldn't conflict with a custom xinput DLL for other use.

In the unlikely event you have any problems just uninstall DirtFix and it will be deactivated.

**Comment by JonnyThree** [comment]
ok thanks, but the dirtfix is actually working if i use the x360ce with his xinput9_1_0.dll?
in other words, the game internal 2 seconds checking of present controllers is deactivated with the use of ditfix and x360ce in the same time?

**Comment by simonowen** [comment]
There should be no problem using both at the same time. DirtFix will still be active.

**Comment by JonnyThree** [comment]
ok thanks so much for your support :)
