### ISSUE TITLE
F1 2019

### ISSUE THREAD

**Issue by SteveRawlinson** [simonowen/dirtfix#4]
Is there any chance this fix might also work with F1 2019? I'd like to give it a go but it currently complains that it's not a dirt game (which is fair enough).

**Comment by simonowen** [comment]
I've wondered whether other games might share the same input polling code and be affected by the same issue.

The complaint you ran into is just a front-end restriction, and if you manually copy (and rename) the appropriate dinput8 DLL file it will still work.  To help identify whether other games are affected I've created [debug versions](https://github.com/simonowen/dirtfix/releases/download/v1.5/DebugFiles.zip) of the dinput modules, which play a sound whenever the input devices are polled.

The last Codemaster F1 game I bought was F1 2010, as my driving setup is VR-only now, and not near my desktop monitor. That game isn't affected, and only plays a single "ding" sound when the game is first loaded. It'd still be worth checking F1 2019, which will need dinput8_64.dll to be renamed to dinput8.dll in the game directory.

If other games are found I'll relax the DiRT file check and add support for them.

**Comment by SteveRawlinson** [comment]
As you suspected, F1 2019 is not affected by the same problem. Applying the .dll makes no difference. It must be something else.

Thanks very much for your reply (and this code which works in dirt 2.0 for me).

**Comment by simonowen** [comment]
I've just realised the diagnostic files were wrong.  It was only beeping when calls were passed through to the real function, so when DirtFix stopped the calls the beeps would stop too.

I've uploaded a [fixed version](https://github.com/simonowen/dirtfix/releases/download/v1.5/DebugFiles_20191029.zip) of the debug archive.  Could you please give it one more try?

I've just tested with GRID Autosport, which is definitely polling.  I'm going to reinstall F1 2010 to re-test that.

**Comment by SteveRawlinson** [comment]
I am happy to try that my conclusion that F1 2019 is not affected is based on installing your dll and noting that the regular freezes still occur.  I didn't actually try the debug version. I'll give it a go tonight.

**Comment by simonowen** [comment]
F1 2010 is still in the clear, and it seems likely the later versions are unaffected too.  I'll add GRID Autosport, and leave the EXE matching open for other manually-added GRID games.

How regular is the freezing in F1 2019?  If's it's very regular I could probably lead you through creating a profiling snapshot to analyze it in the same way I did for the DiRT games.  The output files can be a few hundred MB in size, but they might point to another issue that could be fixed or worked around.

**Comment by SteveRawlinson** [comment]
It's not regular at all. I was frankly clutching at straws, I thought that maybe some of the freezes were too short to be noticed. I'm not surprised this did not solve the problem.

It does seem to be performance related in that if I play on a single monitor in ultra-low settings it freezes less than on 3 monitors at high settings, but the frame rates are normally 60+ so it's not simply a question of needing more GPU horsepower.

I'm happy to create a profiling snapshot and give you the output if you think it would be worth your time. However, I have a suspicion that moving to DX12 will solve it. I'm still on windows 7. I'm going to create a Win 10 partition I think. If that doesn't solve it then maybe it's worth pursuing.

**Comment by SteveRawlinson** [comment]
I put the fixed version of the debug dll in last night and did not hear any additional sounds at all. 

Just to check I've got this right:

![image](https://user-images.githubusercontent.com/964488/67851933-689b6980-fb03-11e9-8a79-0ceb0ac9b35d.png)

**Comment by simonowen** [comment]
Thanks for confirming Steve.  The installation looks good, so I'm happy F1 2019 isn't affected by the original input glitch.

If you're still interested in me looking at your other glitch, I've got some notes on what to do below. I've tried to simplify it with a 3rd party UI tool (created by a Chrome developer), but it's still a bit fiddly. If at any point you think it's too much trouble then feel free to give up!  :)

- Download the [UIforETW](https://github.com/google/UIforETW/releases/download/v1.52/etwpackage1.52.zip) package from GitHub, and extract it somewhere.
- Run `bin\UIforETW.exe`, which should prompt for elevation (needed to capture system events).

The first run will also launch the installer for Microsoft's Windows Performance Toolkit (WPTx64). This can later be uninstalled from Add/Remove Programs at the end of the tests to save a little disk space. It's only active when the tool is in use, so being installed doesn't affect performance.

- On the right, change the drop-down menu from "Tracing to file" to "Circular buffer tracing".
- Click the _Start Tracing_ button (or press Ctrl-Win-R), then minimise the utility.

If you encounter an error about a file being in use, click _Cancel Tracing_, go into the _Settings..._ option and select "Use other kernel logger", then try _Start Tracing_ again.

- Start F1 2019 and play as normal.
- When a game glitch occurs press Ctrl-Win-R to save the buffered trace log to disk.
- Alt-Tab back to Window (or quit the game) and switch back to UI for ETW, where you should find a new entry in the Traces window.
- Right-click on it and select Rename, and give it a name that includes the delay between the issue and the trace capture, such as "glitch 2 seconds ago".
- Right-click again and select Browse Folder to open an Explorer window.
- Right-click the .etl trace file from above and select _Send To_ -> _Compressed (zipped) Folder_.
- Upload the zip file to a service like Google Drive, and email a shared link to it to me at simon@simonowen.com for analysis.

There's no captured keyboard input, but there could be file paths in the dump that could contain names etc. For that reason I usually recommend private sharing of the dumps, just in case.
